version: "3.9"
services:
  persistence-sql:
    depends_on:
      - db-sql
    image: "ostabo/persistence:latest"
    ports:
      - "9091:9091"
    environment:
      - DB_HOST=db-sql
      - DB_IMPLEMENTATION=sql
      - DB_PORT=3306
  persistence-mongo:
    depends_on:
      - db-mongo
    image: "ostabo/persistence:latest"
    ports:
      - "9092:9092"
    environment:
      - PORT=9092
      - DB_HOST=db-mongo
      - DB_IMPLEMENTATION=mongodb
      - DB_PORT=27017
  db-sql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: hexxagon
  db-mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: hexxagon
