ignore:
  - "**/GUI.scala"
  - "**/GuiService.scala"
  - "**/TuiService.scala"
  - "**/resources"
  - "**/PersistenceModule.scala"
  - "**/ProviderModule.scala"
coverage:
  status:
    patch:
      default:
        target: 75%
