ignore:
  - "**/TuiService.scala"
  - "**/CoreRestService.scala"
  - "**/CoreRestClient.scala"
  - "**/PersistenceModule.scala"
  - "**/PersistenceRestService.scala"
  - "**/FileIORestClient.scala"
  - "**/ProviderModule.scala"
  - "**/Http.scala"
  - "**/slick/**"
  - "**/mongoDB/**"
  - "**/DAOInterface.scala"
coverage:
  status:
    patch:
      default:
        target: 75%
