ignore:
  - "**/TuiService.scala"
  - "**/CoreRestService.scala"
  - "**/CoreRestClient.scala"
  - "**/PersistenceModule.scala"
  - "**/PersistenceRestService.scala"
  - "**/FileIORestClient.scala"
  - "**/ProviderModule.scala"
  - "**/Http.scala"
  - "**/DAOSlick.scala"
  - "**/tables/**"
coverage:
  status:
    patch:
      default:
        target: 75%
