version: "3.9"
name: "hexxagon"
services:
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    container_name: hexxagon-database
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hexxagon
      MYSQL_USER: user
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
      DATABASE_HOST:
  gui:
    container_name: "gui"
    network_mode: "host"
    depends_on:
      - core
    image: "ostabo/gui:latest"
    volumes:
      - ~/.ivy2/local:/root/.ivy2/local
    environment:
      - DISPLAY=host.docker.internal:0.0
  tui:
    container_name: "tui"
    depends_on:
      - core
    image: "ostabo/tui:latest"
    stdin_open: true
    environment:
      - HOST=core
  core:
    container_name: "core"
    depends_on:
      - persistence
    image: "ostabo/core:latest"
    ports:
      - "9090:9090"
    environment:
      - HOST=persistence
  persistence:
    container_name: "persistence"
    image: "ostabo/persistence:latest"
    working_dir: /fileio
    ports:
      - "9091:9091"
    volumes:
      - ./:/fileio:xro
