version: "3.9"
name: "hexxagon"
services:
  gui:
    container_name: "gui"
    depends_on:
      - core
    image: "ostabo/gui:latest"
    environment:
      - HOST=core
      - DISPLAY=host.docker.internal:0.0
  tui:
    container_name: "tui"
    depends_on:
      - core
    image: "ostabo/tui:latest"
    stdin_open: true
    environment:
      - HOST=core
  core:
    container_name: "core"
    depends_on:
      - persistence
    image: "ostabo/core:latest"
    ports:
      - "9090:9090"
    environment:
      - HOST=persistence
  persistence:
    container_name: "persistence"
    image: "ostabo/persistence:latest"
    working_dir: /fileio
    ports:
      - "9091:9091"
    volumes:
      - ./:/fileio:xro
