version: "3.9"
name: "hexxagon"
services:
  gui:
    container_name: "gui"
    network_mode: "host"
    depends_on:
      - core
    image: "ostabo/gui:latest"
    volumes:
      - ~/.ivy2/local:/root/.ivy2/local
    environment:
      - DISPLAY=host.docker.internal:0.0
  tui:
    container_name: "tui"
    depends_on:
      - core
    image: "ostabo/tui:latest"
    stdin_open: true
    environment:
      - HOST=core
  core:
    container_name: "core"
    depends_on:
      - persistence
    image: "ostabo/core:latest"
    ports:
      - "9090:9090"
    environment:
      - HOST=persistence
  persistence:
    container_name: "persistence"
    depends_on:
      - db
    image: "ostabo/persistence:latest"
    working_dir: /fileio
    ports:
      - "9091:9091"
    volumes:
      - ./:/fileio:xro
    environment:
      - DB_HOST=db
      #- DB_IMPLEMENTATION=mysql
      - DB_IMPLEMENTATION=mongodb
      - DB_PORT=27017
  #db:
  #  image: mysql:latest
  #  ports:
  #    - "3306:3306"
  #  container_name: db
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_USER: user
  #    MYSQL_PASSWORD: root
  #    MYSQL_DATABASE: hexxagon
  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: hexxagon
