FROM sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.8.2_3.2.2
RUN apt-get update && apt-get install -y --no-install-recommends openjfx && apt-get install -y csh && apt-get install -y libgl1 && apt-get install -y libx11-6 && rm -rf /var/lib/apt/lists/*
WORKDIR /gui
COPY . .
CMD sbt run

